// Auto-generated from GulfFast sitemap analysis. Do not hand-edit casually — regenerate from source data instead.

export interface EquipmentCategory {
  name: string;
  slug: string;
  tier: 1 | 2;
  /** SEO landing-page keyword phrases; only populated for Tier 1 categories, one page per keyword x city */
  landingKeywords: string[];
  /** number of GulfFast-owned units in this category, from the fleet register */
  ownedFleetCount: number;
  /** honest capability range, e.g. "1.5 t to 50 t"; populated for Tier 1 categories only */
  specSummary?: string;
}

export const equipmentCategories: EquipmentCategory[] = [
  { name: "Flatbed Trailers", slug: "flatbed-trailers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Agricultural & Forestry Equipment", slug: "agricultural-and-forestry-equipment", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Agricultural Trailers", slug: "agricultural-trailers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Agriculture Equipment", slug: "agriculture-equipment", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Air Compressors", slug: "air-compressors", tier: 1, landingKeywords: ["Air Compressor Rental"], ownedFleetCount: 1, specSummary: "350 CFM to 750 CFM · towable & skid-mounted" },
  { name: "Ambulances", slug: "ambulances", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Asphalt Equipment", slug: "asphalt-equipment", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Attachments", slug: "attachments", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "ATVs", slug: "atvs", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Backhoe Loaders", slug: "backhoe-loaders", tier: 1, landingKeywords: ["Backhoe Loader Rental"], ownedFleetCount: 0, specSummary: "4WD · loader bucket & rear excavator arm · extendahoe options" },
  { name: "Buses", slug: "buses", tier: 1, landingKeywords: ["Bus Rental"], ownedFleetCount: 3, specSummary: "15 to 50 seats · mini-bus, coaster & full-size" },
  { name: "Cars", slug: "cars", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Chippers", slug: "chippers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Cold Milling Machines", slug: "cold-milling-machines", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Commercial Vehicles", slug: "commercial-vehicles", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Compaction Equipment", slug: "compaction-equipment", tier: 1, landingKeywords: ["Compaction Roller Rental"], ownedFleetCount: 2, specSummary: "10 t to 15 t roller compactors · plate compactors also available" },
  { name: "Compressors", slug: "compressors", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Concrete Equipment", slug: "concrete-equipment", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Concrete Pumps", slug: "concrete-pumps", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Container Handlers", slug: "container-handlers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Containers", slug: "containers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Coolers", slug: "coolers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Cranes", slug: "cranes", tier: 1, landingKeywords: ["Crane Rental"], ownedFleetCount: 2, specSummary: "20 t to 55 t capacity · mobile & pick-and-carry" },
  { name: "Crawler Loaders", slug: "crawler-loaders", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Crushers & Screens", slug: "crushers-and-screens", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Cultivators", slug: "cultivators", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Cutters", slug: "cutters", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Demolition Equipment", slug: "demolition-equipment", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Disk Harrows", slug: "disk-harrows", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Dozers", slug: "dozers", tier: 1, landingKeywords: ["Bulldozer Rental"], ownedFleetCount: 0, specSummary: "D4 to D9 class · straight & U-blade configurations" },
  { name: "Drilling Equipment", slug: "drilling-equipment", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Excavators", slug: "excavators", tier: 1, landingKeywords: ["Excavator Rental"], ownedFleetCount: 0, specSummary: "1.5 t to 50 t · crawler & wheeled · breaker attachments available" },
  { name: "Feeders", slug: "feeders", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Generators", slug: "generators", tier: 1, landingKeywords: ["Generator Rental"], ownedFleetCount: 1, specSummary: "50 kVA to 1,000 kVA · silenced & standard enclosures" },
  { name: "Harvesters", slug: "harvesters", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Hoists", slug: "hoists", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Industrial Balers", slug: "industrial-balers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Lifts", slug: "lifts", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Light Towers", slug: "light-towers", tier: 1, landingKeywords: ["Light Tower Rental"], ownedFleetCount: 1, specSummary: "4,000 W tower lights · diesel-powered, trailer-mounted" },
  { name: "Logging Equipment", slug: "logging-equipment", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Military Vehicles", slug: "military-vehicles", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Mining Equipment", slug: "mining-equipment", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Miscellaneous Equipment", slug: "miscellaneous-equipment", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Motor Graders", slug: "motor-graders", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Mowers", slug: "mowers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Mulcher Tractors", slug: "mulcher-tractors", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Pallet Stackers", slug: "pallet-stackers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Paper Cutting Machines", slug: "paper-cutting-machines", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Pavers", slug: "pavers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Pickup Trucks", slug: "pickup-trucks", tier: 1, landingKeywords: ["Pickup Truck Rental"], ownedFleetCount: 2, specSummary: "Single & double cabin · 4x2 and 4x4 configurations" },
  { name: "Piling Equipment", slug: "piling-equipment", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Pipelayers", slug: "pipelayers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Plants", slug: "plants", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Plows", slug: "plows", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Porta Cabins", slug: "porta-cabins", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Pull Scrapers", slug: "pull-scrapers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Rakes", slug: "rakes", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Reachstackers", slug: "reachstackers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Road Reclaimers", slug: "road-reclaimers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Round Balers", slug: "round-balers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Scrapers", slug: "scrapers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Seeders", slug: "seeders", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Service Vehicles", slug: "service-vehicles", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Site Dumpers", slug: "site-dumpers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Skid Steer Loaders", slug: "skid-steer-loaders", tier: 1, landingKeywords: ["Skid Steer Loader Rental"], ownedFleetCount: 1, specSummary: "Wheeled & compact-track platforms · attachment-ready" },
  { name: "Snow Throwers", slug: "snow-throwers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Spare Parts", slug: "spare-parts", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Sweepers", slug: "sweepers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Tracked Dumpers", slug: "tracked-dumpers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Tractors", slug: "tractors", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Trailers", slug: "trailers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Tree Spades & Stump Cutters", slug: "tree-spades-and-stump-cutters", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Trenchers", slug: "trenchers", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Trucks", slug: "trucks", tier: 1, landingKeywords: ["Water Tanker Rental", "Dump Truck Rental"], ownedFleetCount: 10, specSummary: "16 m³ to 24 m³ dump trucks · 6 t to 10 t boom trucks · water & diesel tankers" },
  { name: "Utility Vehicles", slug: "utility-vehicles", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Vans", slug: "vans", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Waste Conveyors", slug: "waste-conveyors", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Waste Plants", slug: "waste-plants", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Waste Shredders", slug: "waste-shredders", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
  { name: "Welding Sets", slug: "welding-sets", tier: 1, landingKeywords: ["Welding Machine Rental"], ownedFleetCount: 1, specSummary: "Up to 400 A · electric & engine-driven sets" },
  { name: "Wheel Loaders", slug: "wheel-loaders", tier: 1, landingKeywords: ["Wheel Loader Rental"], ownedFleetCount: 0, specSummary: "1.0 m³ to 5.0 m³ bucket · quick-coupler options" },
  { name: "Forklifts", slug: "forklifts", tier: 1, landingKeywords: ["Forklift Rental"], ownedFleetCount: 3, specSummary: "7 t to 10 t capacity · diesel counterbalance" },
  { name: "Telehandlers", slug: "telehandlers", tier: 1, landingKeywords: ["Telehandler Rental"], ownedFleetCount: 0, specSummary: "Extendable telescopic boom · dry-hire & operated options" },
  { name: "Scissor Lifts", slug: "scissor-lifts", tier: 1, landingKeywords: ["Scissor Lift & Man Lift Rental"], ownedFleetCount: 0, specSummary: "Electric & diesel platforms · scissor and man-lift configurations" },
  { name: "Man Lifts", slug: "man-lifts", tier: 2, landingKeywords: [], ownedFleetCount: 0 },
];
