// Auto-generated from GulfFast sitemap analysis. Do not hand-edit casually — regenerate from source data instead.

export interface FleetItem {
  itemName: string;
  spec: string;
  year: string;
  make: string;
  category: string; // matches EquipmentCategory.name
  recordType: "Owned Fleet Asset" | "Equipment Type Reference";
}

export const fleetReference: FleetItem[] = [
  { itemName: "Air Compressor", spec: "750 CFM", year: "", make: "", category: "Air Compressors", recordType: "Equipment Type Reference" },
  { itemName: "Air Compressor", spec: "350 CFM", year: "", make: "", category: "Air Compressors", recordType: "Equipment Type Reference" },
  { itemName: "Bulldozer", spec: "", year: "", make: "", category: "Dozers", recordType: "Equipment Type Reference" },
  { itemName: "Motor Grader", spec: "", year: "", make: "", category: "Motor Graders", recordType: "Equipment Type Reference" },
  { itemName: "Concrete Mixer", spec: "", year: "", make: "", category: "Concrete Equipment", recordType: "Equipment Type Reference" },
  { itemName: "Sky Climber (Suspended Access Cage)", spec: "Big/Cage", year: "", make: "", category: "Lifts", recordType: "Equipment Type Reference" },
  { itemName: "Pipe Threading Machine", spec: "", year: "", make: "", category: "Attachments", recordType: "Equipment Type Reference" },
  { itemName: "Tractor Trailer", spec: "", year: "", make: "", category: "Trailers", recordType: "Equipment Type Reference" },
  { itemName: "Jeep", spec: "4-Wheel Drive", year: "", make: "", category: "Cars", recordType: "Equipment Type Reference" },
  { itemName: "Passenger Bus", spec: "", year: "", make: "", category: "Buses", recordType: "Equipment Type Reference" },
  { itemName: "Sedan Car", spec: "", year: "", make: "", category: "Cars", recordType: "Equipment Type Reference" },
  { itemName: "Pickup Truck", spec: "", year: "", make: "", category: "Pickup Trucks", recordType: "Equipment Type Reference" },
  { itemName: "Mini Bus / Coaster", spec: "", year: "", make: "", category: "Buses", recordType: "Equipment Type Reference" },
  { itemName: "Mini Truck", spec: "", year: "", make: "", category: "Trucks", recordType: "Equipment Type Reference" },
  { itemName: "Mini Dump Truck", spec: "", year: "", make: "", category: "Trucks", recordType: "Equipment Type Reference" },
  { itemName: "Plate Compactor", spec: "", year: "", make: "", category: "Compaction Equipment", recordType: "Equipment Type Reference" },
  { itemName: "Water Tanker", spec: "", year: "", make: "", category: "Trucks", recordType: "Equipment Type Reference" },
  { itemName: "Welding Machine", spec: "Electric", year: "", make: "", category: "Welding Sets", recordType: "Equipment Type Reference" },
  { itemName: "Mobile Crane", spec: "20-50 Ton", year: "", make: "", category: "Cranes", recordType: "Equipment Type Reference" },
  { itemName: "Backhoe (Excavator)", spec: "", year: "", make: "", category: "Excavators", recordType: "Equipment Type Reference" },
  { itemName: "Backhoe (Loader)", spec: "", year: "", make: "", category: "Backhoe Loaders", recordType: "Equipment Type Reference" },
  { itemName: "Boom / Bucket Truck", spec: "", year: "", make: "", category: "Trucks", recordType: "Equipment Type Reference" },
  { itemName: "Generator", spec: "Small/Big", year: "", make: "", category: "Generators", recordType: "Equipment Type Reference" },
  { itemName: "Hydro-Jetting Pump", spec: "", year: "", make: "", category: "Attachments", recordType: "Equipment Type Reference" },
  { itemName: "Concrete Vibrator", spec: "", year: "", make: "", category: "Concrete Equipment", recordType: "Equipment Type Reference" },
  { itemName: "Steel Bending Machine", spec: "", year: "", make: "", category: "Attachments", recordType: "Equipment Type Reference" },
  { itemName: "Painting Machine", spec: "", year: "", make: "", category: "Attachments", recordType: "Equipment Type Reference" },
  { itemName: "Payloader", spec: "Mini/Big", year: "", make: "", category: "Wheel Loaders", recordType: "Equipment Type Reference" },
  { itemName: "Diesel Tanker", spec: "", year: "", make: "", category: "Trucks", recordType: "Equipment Type Reference" },
  { itemName: "Dump Truck", spec: "16 CM", year: "1990", make: "Volvo", category: "Trucks", recordType: "Owned Fleet Asset" },
  { itemName: "Dump Truck", spec: "24 CM", year: "1998", make: "Mercedes", category: "Trucks", recordType: "Owned Fleet Asset" },
  { itemName: "Skid Loader", spec: "", year: "2005", make: "Caterpillar", category: "Skid Steer Loaders", recordType: "Owned Fleet Asset" },
  { itemName: "Boom Truck", spec: "10 Ton", year: "2001", make: "Man", category: "Trucks", recordType: "Owned Fleet Asset" },
  { itemName: "Boom Truck", spec: "6 Ton", year: "2001", make: "Man", category: "Trucks", recordType: "Owned Fleet Asset" },
  { itemName: "Water Tanker", spec: "18,000 Litre", year: "1995", make: "Mercedes", category: "Trucks", recordType: "Owned Fleet Asset" },
  { itemName: "Sweet Water Tanker", spec: "32,000 Litre", year: "1996", make: "Volvo", category: "Trucks", recordType: "Owned Fleet Asset" },
  { itemName: "Sewage & Chemical Vacuum Tank", spec: "", year: "1996", make: "Mercedes", category: "Trucks", recordType: "Owned Fleet Asset" },
  { itemName: "Diesel Tanker", spec: "6,000 Litre", year: "2008", make: "Toyota", category: "Trucks", recordType: "Owned Fleet Asset" },
  { itemName: "Crane", spec: "50 Ton", year: "2002", make: "Kato", category: "Cranes", recordType: "Owned Fleet Asset" },
  { itemName: "Crane", spec: "55 Ton", year: "2009", make: "Sanny", category: "Cranes", recordType: "Owned Fleet Asset" },
  { itemName: "Mini Bus", spec: "15 Seater", year: "2011", make: "Toyota", category: "Buses", recordType: "Owned Fleet Asset" },
  { itemName: "Coaster Bus", spec: "30 Seater", year: "2010", make: "Toyota", category: "Buses", recordType: "Owned Fleet Asset" },
  { itemName: "Bus", spec: "50 Seater", year: "1996", make: "GMC", category: "Buses", recordType: "Owned Fleet Asset" },
  { itemName: "Pick-Up (Double Cabin)", spec: "", year: "2010", make: "Toyota", category: "Pickup Trucks", recordType: "Owned Fleet Asset" },
  { itemName: "Pick-Up (Single Cabin)", spec: "", year: "2010", make: "Toyota", category: "Pickup Trucks", recordType: "Owned Fleet Asset" },
  { itemName: "Truck", spec: "7 Ton", year: "2008", make: "Isuzu", category: "Trucks", recordType: "Owned Fleet Asset" },
  { itemName: "Truck", spec: "3.5 Ton", year: "2004", make: "Mitsubishi", category: "Trucks", recordType: "Owned Fleet Asset" },
  { itemName: "Generator", spec: "50 kV - 1000 kV", year: "", make: "Caterpillar", category: "Generators", recordType: "Owned Fleet Asset" },
  { itemName: "Tower Light", spec: "4000 Watt", year: "2011", make: "Terex", category: "Light Towers", recordType: "Owned Fleet Asset" },
  { itemName: "Air Compressor", spec: "375 CFM", year: "2011", make: "Sullair", category: "Air Compressors", recordType: "Owned Fleet Asset" },
  { itemName: "Forklift", spec: "10 Ton (FL-002)", year: "2010", make: "Doosan", category: "Forklifts", recordType: "Owned Fleet Asset" },
  { itemName: "Forklift", spec: "10 Ton (FL-003)", year: "2011", make: "Doosan", category: "Forklifts", recordType: "Owned Fleet Asset" },
  { itemName: "Forklift", spec: "7 Ton", year: "2010", make: "Doosan", category: "Forklifts", recordType: "Owned Fleet Asset" },
  { itemName: "Roller Compactor", spec: "10 Ton", year: "2010", make: "Bomag", category: "Compaction Equipment", recordType: "Owned Fleet Asset" },
  { itemName: "Roller Compactor", spec: "15 Ton", year: "2010", make: "Bomag", category: "Compaction Equipment", recordType: "Owned Fleet Asset" },
  { itemName: "Welding Machine", spec: "400 Amp", year: "2010", make: "Lincoln", category: "Welding Sets", recordType: "Owned Fleet Asset" },
  { itemName: "Forklift", spec: "", year: "", make: "", category: "Forklifts", recordType: "Equipment Type Reference" },
  { itemName: "Telehandler", spec: "", year: "", make: "", category: "Telehandlers", recordType: "Equipment Type Reference" },
  { itemName: "Scissor Lift", spec: "", year: "", make: "", category: "Scissor Lifts", recordType: "Equipment Type Reference" },
  { itemName: "Man Lift", spec: "", year: "", make: "", category: "Man Lifts", recordType: "Equipment Type Reference" },
  { itemName: "Hiace Van", spec: "", year: "", make: "", category: "Vans", recordType: "Equipment Type Reference" },
  { itemName: "Coaster (Mini Bus)", spec: "", year: "", make: "", category: "Buses", recordType: "Equipment Type Reference" },
  { itemName: "Bobcat (Compact Loader)", spec: "", year: "", make: "", category: "Skid Steer Loaders", recordType: "Equipment Type Reference" },
  { itemName: "Shovel Loader", spec: "", year: "", make: "", category: "Wheel Loaders", recordType: "Equipment Type Reference" },
];
